APT::FTPArchive::Release {
  Origin "Aenigma";
  Label "Aenigma";
  Suite "stable";
  Codename "stable";
  Architectures "amd64 arm64 all";
  Components "main";
  Description "Repository containing packages for Aenigma - Federated messaging system";
};
